### ISSUE TITLE
CSS gradient

### ISSUE THREAD

**Issue by shreejalmaharjan-27** [fusengine/apaxy-v2#1]
I'm not able to add CSS gradient by modifying the CSS file. Please help

**Comment by fusengine** [comment]
Give a screen please.

**Comment by shreejalmaharjan-27** [comment]
> Give a screen please.

How can I add this CSS gradient as background color of my site?:
background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(10,10,255,1) 35%, rgba(1,212,255,1) 100%);
